import { Inter, Poppins , Montserrat} from "next/font/google";

import Navbar from "./Component/navbar/Navbar";
import Sidebar from "./Component/sidebar/Sidebar.jsx"
import Footer from "./Component/footer/Footer";
import AuthProvider from "./providers/AuthProvider";
import "./global.css"
import ToTop from "./Component/toTop/ToTop";
const montserrat = Montserrat({ subsets: ["latin"],
  weight:["400","400","600","700"]
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:'https://i.pinimg.com/564x/3c/9e/4b/3c9e4b32b67d641965915ee08db63844.jpg'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>


      <AuthProvider>
       <div className="container ">
          {/* the sidebar  */}
        
        
    

        
          <Navbar/>
          <Sidebar/>
           {children}
      



      
       </div>
       <ToTop/>
       <Footer/>
      
       </AuthProvider>
        </body>
    </html>
  );
}
