import React from 'react'
import FormRegister from './FormRegister';
import "../registerLogin.css"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFacebook, faGithub, faGoogle, faTwitter } from '@fortawesome/free-brands-svg-icons';
import Link from 'next/link';


export const metadata = {
  title: "register new user",
  description: "Generated by create next app",

};
function page() {
  return (
    <div className='register-login'>
      <div className="register-login-header">
        <h1>register</h1>
        <p>hi dear user welcome back 👋 login to your accounts to have access to more features  💝</p>
        <span className='text-slate-700 capitalize'>have account in accsBulk ? <Link href='/Login' className='text-violet-400 capitalize'> login </Link></span>
      </div>
      
        <div className="register-login-methods">
          <div className='google '><FontAwesomeIcon className='text-orange-500'  width={"20px"} icon={faGoogle} /></div>
          <div className='facebook bg-blue-600'><FontAwesomeIcon   width={"20px"}  icon={faFacebook} /></div>
          <div className='redbuble bg-blue-400'><FontAwesomeIcon width={"20px"} icon={faTwitter} /></div>
          <div className='github bg-black'><FontAwesomeIcon  width={"20px"}   icon={faGithub} /></div>
        </div>
         <div className="lines">
          <div className="line"></div>
          <span>or</span>
          <div className="line"></div>
         </div>
             

             {/* form for registeration====== */}
             <FormRegister/>


    </div>
  )
}

export default page
