import "./about.css"
export const metadata = {
  title: "about us",
  description: "Generated by create next app",

};
function page() {
  return (
    <div>
    <a href="">about</a>  
    </div>
  )
}

export default page
